name: CI & Publish NPM Package

on:
  push:
    branches:
      - main

env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
      - run: npm ci

      - name: Run tests
        run: npm test

      - name: Release version
        run: npm run release

      - name: Check if package.json changed
        id: pkg
        run: |
          git fetch origin main
          git diff --quiet origin/main package.json || echo "::set-output name=changed::true"

      - name: Publish to NPM
        if: steps.pkg.outputs.changed == 'true'
        run: npm publish --access public